name: "Google Drive Downloader"
on:
  workflow_dispatch:
jobs:
  example_google_drive_download:
    runs-on: ubuntu-latest
    steps:
      - name: Acquire Google access token
        id: google-access-token
        uses: playeveryware/action-google-access-token@v1
        with:
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          scope: 'https://www.googleapis.com/auth/drive.readonly'

      - name: Download file
        uses: playeveryware/action-google-drive-download@v1
        with:
          token: ${{ steps.google-access-token.outputs.token }}
          file-id: 1wpafHx0xhiPPGnwjOI3xpw_XchLpn-OG
          path: test.bin

      - name: Show file information
        run: |
          ls test.bin
          du test.bin
